version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - ./app:/app
      - static_volume:/app/build
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=app.settings
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
    depends_on:
      - rabbitmq
      - db

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/build
    depends_on:
      - app

  celery:
    build:
      context: .
      dockerfile: celery/Dockerfile
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=app.settings
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
    depends_on:
      - app
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: mariadb:10.5
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
      - MYSQL_ROOT_PASSWORD=rootpassword

volumes:
  static_volume:
  mariadb_data:
