version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    volumes:
    - ./app:/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
  celery:
    build:
      context: .
      dockerfile: celery/Dockerfile
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - app
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
